### ISSUE TITLE
The failover.sh script can not work with MRM 0.52 version

### ISSUE THREAD

**Issue by jerrylin0** [mariadb-corporation/replication-manager#7]
Hi ,
I am testing the MRM 0.52 version.
I using the failover.sh script to failover (https://mariadb.com/blog/mariadb-automatic-failover-maxscale-and-mariadb-replication-manager) , and I also change the failover option = 'force'.
When the master down ,I got a message : "ERROR: None of the switchover or failover modes are set." 
Then I output the cmd command ,the command can't get the $nodelist variable .

How should I fix my issue?
Thank you.

**Comment by tanji** [comment]
Don't use 0.52 it is buggy for failover, I will release a new version later today.

**Comment by jerrylin0** [comment]
Hi ,
Thank you .
Waiting for your good news .

**Comment by tanji** [comment]
Hi Jerrylin,

Try the new 0.6.0 version: https://github.com/mariadb-corporation/replication-manager/releases/tag/0.6.0-dev

The flags have been changed to POSIX compatible (-- instead of -) so make sure to change at.

Also see https://github.com/mariadb-corporation/replication-manager/blob/0.6/README.md for new options.

This version has been very stable for me and corrects many bugs present in 0.5.2.

**Comment by jerrylin0** [comment]
Hi Guillaume,

Thank you .
I will test this version .

**Comment by tanji** [comment]
Hi @jerrylin0 , 
Please try the latest version and tell me if it fixes your issues.

**Comment by tanji** [comment]
Hi @jerrylin0,

try version 0.6.2, it should fix the bug that you encountered.
